/**
 * 
 * Constantes para tipo de tramite
 */

export default {
    AMPLIACION:"AMPLIACION",
    ANTIGUO_RESIDENTE:"ANTIGUO RESIDENTE",
    ARRAIGO:"ARRAIGO",
    REGISTRO_DE_ARRAIGO:"REGISTRO DE ARRAIGO",
    LEVANTAMIENTO_DE_ARRAIGO_DEFINITIVO : "LEVANTAMIENTO DE ARRAIGO DEFINITIVO",
    LEVANTAMIENTO_DE_ARRAIGO_TEMPORAL: "LEVANTAMIENTO DE ARRAIGO TEMPORAL",

    AUTORIZACION_SALIDA:"AUTORIZACION SALIDA",
    CEDULA_DE_EXTRANJERO:"CEDULA DE EXTRANJERO",
    CERTIFICACION:"CERTIFICACION",
    CERTIFICADO_DE_NACIMIENTO:"CERTIFICADO DE NACIMIENTO",
    COMPLEMENTACION_DE_MOVIMIENTO_O_FLUJO_MIGRATORIO:"COMPLEMENTACION DE MOVIMIENTO O FLUJO MIGRATORIO",
    CONDONACION_DE_MULTAS:"CONDONACION DE MULTAS",
    DIAS:"DIAS",
    DOCUMENTOS:"DOCUMENTOS",
    INVITACIONES:"INVITACIONES",
    LEGALIZACION:"LEGALIZACION",
    MOVIMIENTO_MIGRATORIO:"MOVIMIENTO MIGRATORIO",
    MOVIMIENTO_O_FLUJO_MIGRATORIO:"MOVIMIENTO O FLUJO MIGRATORIO",
    NATURALIZACION:"NATURALIZACION",
    OTROS:"OTROS",
    PASABANDA:"PASABANDA",
    PASAPORTES:"PASAPORTES",
    PERMANENCIA:"PERMANENCIA",
    RECONOCIMIENTO:"RECONOCIMIENTO",
    REGISTRO_DE_NO_ARRAIGO:"REGISTRO DE NO ARRAIGO",
    RESOLUCION_ADMINISTRATIVA:"RESOLUCION ADMINISTRATIVA",
    SALIDA:"SALIDA",
    SANCIONES:"SANCIONES",
    TASAS:"TASAS",
    TRASPASO:"TRASPASO",
    TRIPULANTE:"TRIPULANTE",
    TVF:"TVF",
    VISA:"VISA",
    VISAS:"VISAS",
    COD_TRIPULANTE_RENOVACION_REPOSICION: "DV004LTRE",
}