export default {
    name_app: 'INVENTORY APP',
    crear_cuenta: 'SING UP',
    contactos: 'Contacts',
    consultas: 'Q&A',
    soporte_tecnico: 'Technical Support',
    interno: 'Internal',
    ingresa_a: 'LOGIN TO ',
    usuario: 'USER',
    ingresa_usuario: 'Enter User',
    correo_electronico: 'EMAIL',
    contrasenha: 'PASSWORD',
    ingresa_contrasenha: 'Enter Password',
    iniciar_sesion: 'SING IN',
    recuperar_contrasenha: 'Recover your password!',
    datos_personales: 'PERSONAL INFORMATION',
    bienvenida: 'Welcome to the Virtual Window of the Dirección General de Migración, it is a platform where you can start and/or request available procedures, which can be carried out online.',
    nota: 'Important note!',
    obligatorio: 'It is mandatory to upload',
    aqui_en: 'here in',
    foto_perfil: 'PROFILE PICTURE',
    foto_documento: 'PHOTO OF THE DOCUMENT',

    //datos personales
    info_personal: 'PERSONAL INFORMATION',
    nombre: 'NAMES',
    primer_apellido: 'FIRST LAST NAME',
    segundo_apellido: 'SECOND LAST NAME',
    fecha_nacimiento: 'DATE OF BIRTH',
    tipo_documento: 'DOCUMENT TYPE',
    nro_documento: 'NRO. DOCUMENT',
    nacionalidad: 'NATIONALITY',
    pais_nacimiento: 'COUNTRY OF BIRTH',
    genero: 'GENDER',
    telefono: 'PHONE',
    correo: 'EMAIL',
    direccion: 'ADDRESS',
    correo_confirmado: 'Confirmed email,',
    cuenta_activa: 'activated account',

    // INICIO TRÁMITE
    inicio_tramite: 'START OF PROCEDURE',
    nuevo_tramite: 'NEW PROCEDURE',
    busqueda: 'SEARCH',
    fecha_inicio: 'Start date',
    fecha_fin: 'End date',
    codigo_unico: 'UNIQUE CODE',
    tramite: 'PROCEDURE',
    fecha_inicio_tramite: 'PROCESSING START DATE',
    estado: 'STATUS',
    acciones: 'ACTIONS',
    procesar: 'PROCESS',
    descargar_autorizacion: 'Download Authorization',

    //cancelación de trámite
    campo_requerido:'Required field',
    cancelacion_tramite: 'CANCELLATION OF PROCEDURE',
    motivo_cancelacion: 'REASON FOR CANCELLATION OF THE PROCEDURE',
    cancelar: 'CANCEL',
    aceptar: 'ACCEPT',

    //tramite
    elija_tramite: 'CHOOSE THE PROCEDURE',    
    continuar: 'CONTINUE',
    seleccionar_tramite: 'SELECT THE PROCEDURE YOU WANT TO CARRY OUT',
  
    //subir documento
    datos_tramite: 'PROCEDURE DATA',
    info_tramite: 'PROCEDURE INFORMATION',
    donde_recoger: 'WHERE TO PICK UP THE PROCEDURE',
    ciudad_emision: 'ISSUE CITY',
    info_lugar: 'The place you select is important for',
    info_entrega: 'The delivery of the procedure',
    info_docuemntos: 'Where you must present the original documents',
    type: 'TYPE',
    horarios: 'SCHEDULES',
    ubicacion: 'View location',
    solicitud: 'REQUEST START OF PROCESS',
    requisito: 'REQUIREMENT',
    vista_previa: 'PREVIEW',
    tit_requisitos: 'REQUIREMENTS',

    //requisitos
    tit_requisitos: 'REQUIREMENTS',

    //crear cuenta
    usuario_correo: 'The email will be the username to enter the System.',
    repetir_contrasenha: 'REPEAT PASSWORD',
    registrar: 'REGISTER',
    ya_tiene_cuenta: 'Do you already have an account?',
    inicio_cesion: 'Log in!',
    lugar_nacimiento: 'BIRTHPLACE',
    otro_apellido: 'OTHER_SURNAME',
    indefinido: 'UNDEFINED',
    fecha_emision: 'DOCUMENT ISSUANCE DATE (ONLY IF IT HAS)',
    fecha_expiracion: 'EXPIRATION DATE OF THE DOCUMENT',
    pais_emision: 'COUNTRY OF ISSUANCE',


     //
     search:"Search",
     name:"Name",
     created_at:"Created at",
     save:"Save",
     close:"Close",
     no_items:"No items",
     select:"Elegir",
     //
     category:"Category",
     categories: "Categories",
     new_category: "New Category",
     name_category: "Name´s category",

      //supplier
    suppliers: "Suppliers",
    nit: 'NIT',	
    razon_social: 'Business Name',	
    concact: 'Contact',	
    email: 'Email',	
    phone: 'Phone',	
    address: 'Address',	
    customer: 'Customer',
    supplier: 'Supplier',
    new_supplier: "New Supplier",
    name_supplier: "Supplier Name",
    
    // users
    user: "User",
    users: "Users",
    username: "Username",
    new_user: "New User",
    name_user: "User Name",
    password: "Password",
    password_confirm: "Confirm Password",
    email_user: "Email",
    phone_user: "Phone",
    role: "Role",

    // units
    unit: "Unit",
    units: "Units",
    new_unit: "New Unit",
    name_unit: "Unit Name",
    abbreviation: "Abbreviation",
    
    //products
    product: "Product",
    products: "Products",
    new_product: "New Product",
    name_product: "Product Name",
    product_code: "Product Code",
    purchase_price: "Purchase Price",
    sale_price: "Sale Price",
    stock: "Stock",
    upload_image: "Upload Image",
    barcode: "Barcode",
    manufacturer: "Manufacturer",
    weight: "Weight",
    product_form: "Product Form",

    // income

    income: "Income",
    incomes: "Incomes",
    Income_purchase: "Purchase",
    date: "Date",
    quantity: "Quantity",
    subtotal: "Subtotal",
    total: "Total",
    lote: "Lote",
    expiration: "Expiration Date",

        // outlets
    outlet: "Outlet",
    outlets: "Outlets",
    outlet_sale: "Outlet Sale",

    // orders
    order: "Order",
    orders: "Orders",
    movements: "Movements",
    type_movement: "Movement Type",
    total_amount: "Total Amount",
    items: "Items",
    total_items: "Total Items",
    order_date: "Order Date",
    order_number: "Order Number",
    discount: "Discount",
    price: "Price",
    reports: "Reports",
}