export default {
    name_app: 'INVENTARIO APP',
    crear_cuenta: 'CREAR CUENTA',
    contactos: 'Si tiene consultas',
    consultas: 'Consultas',
    soporte_tecnico: 'Soporte técnico',
    interno: 'Interno',
    ingresa_a: 'INGRESA A',
    usuario: 'USUARIO',
    ingresa_usuario: 'Ingresa usuario',
    correo_electronico: 'CORREO ELECTRÓNICO',
    contrasenha: 'CONTRASEÑA',
    ingresa_contrasenha: 'Ingresa contraseña',
    iniciar_sesion: 'INICIAR SESIÓN',
    recuperar_contrasenha: 'Recuperar Contraseña',
    datos_personales: 'DATOS PERSONALES',
    bienvenida: 'Bienvenido a la Ventanilla Virtual de la Dirección General de Migración, es un plataforma, donde podra iniciar y/o solicitar trámites disponibles, que se pueden realizar en línea.',
    nota: '¡Nota Importante!',
    obligatorio: 'Es obligatorio subir',
    aqui_en: 'aquí en',
    foto_perfil: 'FOTO DE PERFIL,',
    foto_documento: 'FOTO DEL DOCUMENTO',

    //datos personales
    info_personal: 'INFORMACIÓN PERSONAL',
    nombre: 'NOMBRES',
    primer_apellido: 'PRIMER APELLIDO',
    segundo_apellido: 'SEGUNDO APELLIDO',
    fecha_nacimiento: 'FECHA NACIMIENTO',
    tipo_documento: 'TIPO DOCUMENTO',
    nro_documento: 'NRO. DOCUMENTO',
    nacionalidad: 'NACIONALIDAD',
    pais_nacimiento: 'PAIS DE NACIMIENTO',
    genero: 'GÉNERO',
    telefono: 'TELÉFONO',
    correo: 'CORREO ELECTRÓNICO',
    direccion: 'DIRECCIÓN',
    correo_confirmado:'Correo confirmado,',
    cuenta_activa: 'cuenta activada',

    // INICIO TRÁMITE
    inicio_tramite: 'INICIO DE TRÁMITE',
    nuevo_tramite: 'NUEVO TRÁMITE',
    busqueda: 'BÚSQUEDA',
    fecha_inicio: 'Fecha inicio',
    fecha_fin: 'Fecha fin',
    codigo_unico: 'CÓDIGO ÚNICO',
    tramite: 'TRÁMITE',
    fecha_inicio_tramite: 'FECHA INICIO TRÁMITE',
    estado: 'ESTADO',
    acciones: 'ACCIONES',
    procesar: 'PROCESAR',
    descargar_autorizacion: 'Descargar Autorización',

    //cancelación de trámite
    campo_requerido:'Campo requerido',
    cancelacion_tramite: 'CANCELACIÓN DE TRÁMITE',
    motivo_cancelacion: 'MOTIVO DE CANCELACIÓN DEL TRÁMITE',
    cancelar: 'CANCELAR',
    aceptar: 'ACEPTAR',
    
    //tramite
    elija_tramite: 'ELIJA EL TRÁMITE',
    continuar: 'CONTINUAR',
    seleccionar_tramite: 'SELECCIONE EL TRÁMITE QUE DESEA REALIZAR',

    //subir documento
    datos_tramite: 'DATOS DE TRÁMITE',
    info_tramite: 'INFORMACIÓN DEL TRÁMITE',
    donde_recoger: 'DONDE RECOGER EL TRÁMITE',
    ciudad_emision: 'CIUDAD EMISIÓN',
    info_lugar: 'El lugar que seleccione es importante para',
    info_entrega: 'La entrega del trámite',
    info_docuemntos: 'Donde debe presentar los documentos originales',
    tipo: 'TIPO',
    horarios: 'HORARIOS',
    ubicacion: 'Ver ubicación',
    solicitud:'SOLICITAR INICIO DE TRÁMITE',
    requisito:'REQUISITO',
    vista_previa: 'VISTA PREVIA',

    //requisitos
    tit_requisitos: 'REQUISITOS',

    //crear cuenta
    usuario_correo: 'El correo electrónico será el nombre de usuario para ingresar al Sistema.',
    repetir_contrasenha: 'REPITE CONTRASEÑA',
    registrar: 'REGISTRAR',
    ya_tiene_cuenta: '¿Ya tienes una cuenta?',
    inicio_cesion: '¡Iniciar sesión!',
    lugar_nacimiento: 'LUGAR DE NACIMIENTO',
    otro_apellido: 'OTRO_APELLIDO',
    indefinido: 'INDEFINIDO',
    fecha_emision: 'Fecha de emisión de documento (solo si tiene)',
    fecha_expiracion: 'Fecha de expiración del documento',
    pais_emision: 'PAÍS DE EMISIÓN',
}