export default {
  name_app: "INVENTARIO APP",
  crear_cuenta: "CREAR CUENTA",
  contactos: "Si tiene consultas",
  consultas: "Consultas",
  soporte_tecnico: "Soporte técnico",
  interno: "Interno",
  ingresa_a: "INGRESA A",
  usuario: "USUARIO",
  ingresa_usuario: "Ingresa usuario",
  correo_electronico: "CORREO ELECTRÓNICO",
  contrasenha: "CONTRASEÑA",
  ingresa_contrasenha: "Ingresa contraseña",
  iniciar_sesion: "INICIAR SESIÓN",
  recuperar_contrasenha: "Recuperar Contraseña",
  datos_personales: "DATOS PERSONALES",
  bienvenida:
    "Bienvenido a la Ventanilla Virtual de la Dirección General de Migración, es un plataforma, donde podra iniciar y/o solicitar trámites disponibles, que se pueden realizar en línea.",
  nota: "¡Nota Importante!",
  obligatorio: "Es obligatorio subir",
  aqui_en: "aquí en",
  foto_perfil: "FOTO DE PERFIL,",
  foto_documento: "FOTO DEL DOCUMENTO",

  //datos personales
  info_personal: "INFORMACIÓN PERSONAL",
  nombre: "NOMBRES",
  primer_apellido: "PRIMER APELLIDO",
  segundo_apellido: "SEGUNDO APELLIDO",
  fecha_nacimiento: "FECHA NACIMIENTO",
  tipo_documento: "TIPO DOCUMENTO",
  nro_documento: "NRO. DOCUMENTO",
  nacionalidad: "NACIONALIDAD",
  pais_nacimiento: "PAIS DE NACIMIENTO",
  genero: "GÉNERO",
  telefono: "TELÉFONO",
  correo: "CORREO ELECTRÓNICO",
  direccion: "DIRECCIÓN",
  correo_confirmado: "Correo confirmado,",
  cuenta_activa: "cuenta activada",

  // INICIO TRÁMITE
  inicio_tramite: "INICIO DE TRÁMITE",
  nuevo_tramite: "NUEVO TRÁMITE",
  busqueda: "BÚSQUEDA",
  fecha_inicio: "Fecha inicio",
  fecha_fin: "Fecha fin",
  codigo_unico: "CÓDIGO ÚNICO",
  tramite: "TRÁMITE",
  fecha_inicio_tramite: "FECHA INICIO TRÁMITE",
  estado: "ESTADO",
  acciones: "ACCIONES",
  procesar: "PROCESAR",
  descargar_autorizacion: "Descargar Autorización",

  //cancelación de trámite
  campo_requerido: "Campo requerido",
  cancelacion_tramite: "CANCELACIÓN DE TRÁMITE",
  motivo_cancelacion: "MOTIVO DE CANCELACIÓN DEL TRÁMITE",
  cancelar: "CANCELAR",
  aceptar: "ACEPTAR",

  //tramite
  elija_tramite: "ELIJA EL TRÁMITE",
  continuar: "CONTINUAR",
  seleccionar_tramite: "SELECCIONE EL TRÁMITE QUE DESEA REALIZAR",

  //subir documento
  datos_tramite: "DATOS DE TRÁMITE",
  info_tramite: "INFORMACIÓN DEL TRÁMITE",
  donde_recoger: "DONDE RECOGER EL TRÁMITE",
  ciudad_emision: "CIUDAD EMISIÓN",
  info_lugar: "El lugar que seleccione es importante para",
  info_entrega: "La entrega del trámite",
  info_docuemntos: "Donde debe presentar los documentos originales",
  type: "TIPO",
  horarios: "HORARIOS",
  ubicacion: "Ver ubicación",
  solicitud: "SOLICITAR INICIO DE TRÁMITE",
  requisito: "REQUISITO",
  vista_previa: "VISTA PREVIA",

  //requisitos
  tit_requisitos: "REQUISITOS",

  //crear cuenta
  usuario_correo:
    "El correo electrónico será el nombre de usuario para ingresar al Sistema.",
  repetir_contrasenha: "REPITE CONTRASEÑA",
  registrar: "REGISTRAR",
  ya_tiene_cuenta: "¿Ya tienes una cuenta?",
  inicio_cesion: "¡Iniciar sesión!",
  lugar_nacimiento: "LUGAR DE NACIMIENTO",
  otro_apellido: "OTRO_APELLIDO",
  indefinido: "INDEFINIDO",
  fecha_emision: "Fecha de emisión de documento (solo si tiene)",
  fecha_expiracion: "Fecha de expiración del documento",
  pais_emision: "PAÍS DE EMISIÓN",

  //
  search: "Busqueda",
  name: "Nombre",
  created_at: "Registrado en ",
  save: "Guardar",
  close: "Cerrar",
  no_items: "Sin registros",
  select: "Elegir",
  //
  category: "Categoria",
  categories: "Categorías",
  new_category: "Nueva Categoría",
  name_category: "Nombre de Categoría",

  //supplier
  suppliers: "Proveedores",
  nit: "NIT",
  razon_social: "Razon social",
  concact: "contact",
  email: "Correo",
  phone: "Teléfono",
  address: "Dirección",
  customer: "Cliente",
  supplier: "Proveedor",
  new_supplier: "Nuevo Proveedor",
  name_supplier: "Nombre de Proveedor",

  // users
  user: "Usuario",
  users: "Usuarios",
  username: "Nombre de Usuario",
  new_user: "Nuevo Usuario",
  name_user: "Nombre de Usuario",
  password: "Contraseña",
  password_confirm: "Confirmar Contraseña",
  email_user: "Correo Electrónico",
  phone_user: "Teléfono",
  role: "Rol",

  // units
  unit: "Unidad",
  units: "Unidades",
  new_unit: "Nueva Unidad",
  name_unit: "Nombre de Unidad",
  abbreviation: "Abreviatura",

  //products
  product: "Producto",
  products: "Productos",
  new_product: "Nuevo Producto",
  name_product: "Nombre del Producto",
  product_code: "Código del Producto",
  purchase_price: "Precio de Compra",
  sale_price: "Precio de Venta",
  stock: "Existencias",
  upload_image: "Subir Imagen",
  barcode: "Código de Barras",
  manufacturer: "Fabricante",
  weight: "Peso",

  // income
income: "Ingreso",
incomes: "Ingresos",
income_purchase: "Ingreso por compra",
date: "Fecha",
quantity: "Cantidad",
subtotal: "Subtotal",
total: "Total",
lote: "Lote",
expiration: "Fecha de Caducidad",

// oulets
outlet: "Salida",
outlets: "Salidas",
outlet_sale: "Salida por venta",

// orders
order: "Orden",
orders: "Ordenes",
movements: "Movimientos",
type_movement: "Tipo de movimiento",
total_amount: "Total",
items: "Items",
total_items: "Total de productos",
order_date: "Fecha de orden",
order_number: "Número de orden",
discount: "Descuento",
price: "Precio",
reports: "Reportes",

};
